In [1]:
import pandas as pd
import numpy as np
from tqdm.auto import tqdm, trange
import pickle

In [51]:
df = pd.read_csv('simple_collection.csv')

In [93]:
df = df.drop(columns=['dt', 'gather_dt', '_id'])

In [102]:
df.head()

article_content category content_type  \
0  Today, Google launched its second cloud region...      NaN  article_tag   
1  US-based Dun & Bradstreet provides commercial ...      NaN  article_tag   
2  For AI-based software to work well in the real...      NaN  article_tag   
3  \nJennifer Ouellette\n    -  Jul 15, 2021 10:0...      NaN  article_tag   
4  \nDan Goodin\n    -  Jul 15, 2021 7:22 pm UTC\...      NaN  article_tag   

   digest_number download_status is_main  keywords language  \
0            NaN         success     NaN       NaN  ENGLISH   
1            NaN         success     NaN       NaN  ENGLISH   
2            NaN         success     NaN       NaN  ENGLISH   
3            NaN         success     NaN       NaN  ENGLISH   
4            NaN         success     NaN  backdoor  ENGLISH   

                   model     pk  processed processed_tags projects     state  \
0  gatherer.digestrecord  11475      False             []      [1]  FILTERED   
1  gatherer.digestrecord  11476      False             []      [1]  FILTERED   
2  gatherer.digestrecord  11477      False             []      [1]  FILTERED   
3  gatherer.digestrecord  11478      False             []      [1]  FILTERED   
4  gatherer.digestrecord  11479      False             []      [1]  FILTERED   

  subcategory                                              title  \
0         NaN       Google Launches Second Cloud Region In India   
1         NaN  Interview: Avinash Gupta, Managing Director & ...   
2         NaN        How Does Crowdsourcing Data Labelling Work?   
3         NaN  Review: Loki’s surprising twists paid off with...   
4         NaN  For years, a backdoor in popular KiwiSDR produ...   

                                                 url  
0  https://analyticsindiamag.com/google-launches-...  
1  https://analyticsindiamag.com/interview-avinas...  
2  https://analyticsindiamag.com/how-does-crowdso...  
3                 https://arstechnica.com/?p=1780045  
4                 https://arstechnica.com/?p=1780666

In [94]:
df.category.unique()

array([nan, 'NEWS', 'ARTICLES', 'RELEASES', 'OTHER', 'VIDEOS'],
      dtype=object)

In [95]:
df.digest_number.unique()

array([nan, 79., 80., 81.])

In [96]:
df.keywords.unique()

array([nan, 'backdoor', 'AI', 'games', 'CI/CD;DevOps', 'security',
       'Machine learning', 'management', 'threat', 'secure', 'CIP',
       'cybersecurity', 'securing', 'game', 'exam', 'games;MUSIC',
       'malware', 'DevOps;митап', 'уязвимость', 'безопасности',
       'ОС;Astra Linux;Linux', 'vulnerabilities;Open Source',
       'Open Source', 'Redis', 'Open-Source', 'management;Open Source',
       'MUSIC', 'GitHub;Open Source', 'Linux', 'GitHub', 'Android',
       'Audacity', 'KDE;Linux', 'security;vulnerability;Linux',
       'game;KDE;Plasma', 'game;Linux', 'curl', 'Flutter;Linux', 'Wine',
       'QEMU', 'Android;Linux', 'Linux;VirtualBox', 'Ubuntu', 'Tails',
       'Apache;Lighttpd;Nginx', 'KDE', 'management;Red Hat', 'KubeVirt',
       'Kubernetes', 'security;Kubernetes', 'attack;security', 'CNCF',
       'Flux', 'Kuma', 'Docker', 'CI/CD;DevOps;management;Wave',
       'management;CNCF;Cloud Native Computing Foundation;Kubernetes',
       'attack;game;games;secure', 'ML', 'Ku

In [97]:
df.download_status.unique()

array(['success', 'failed'], dtype=object)

In [103]:
df.loc[df.download_status == 'failed']

article_content category            content_type  digest_number  \
477              NaN      NaN                     404            NaN   
485              NaN      NaN                     pdf            NaN   
488              NaN      NaN                     404            NaN   
500              NaN      NaN                     pdf            NaN   
533              NaN      NaN                     pdf            NaN   
...              ...      ...                     ...            ...   
7018             NaN      NaN                   audio            NaN   
7040             NaN      NaN  404 or ConnectionError           81.0   
7469             NaN      NaN  404 or ConnectionError            NaN   
7472             NaN      NaN                   video            NaN   
7597             NaN      NaN                   video            NaN   

     download_status is_main                    keywords language  \
477           failed     NaN                         NaN  ENGLISH   
485           failed     NaN                         NaN  ENGLISH   
488           failed     NaN                         NaN  ENGLISH   
500           failed     NaN                      NetBSD  ENGLISH   
533           failed     NaN                         NaN  ENGLISH   
...              ...     ...                         ...      ...   
7018          failed     NaN                         NaN  ENGLISH   
7040          failed     NaN                     ОС;Альт  RUSSIAN   
7469          failed     NaN            Brave;OpenSource  ENGLISH   
7472          failed     NaN  Machine learning;AI;Docker  ENGLISH   
7597          failed     NaN                         NaN  ENGLISH   

                      model     pk  processed processed_tags projects  \
477   gatherer.digestrecord  11973      False             []      [2]   
485   gatherer.digestrecord  11981      False             []      [2]   
488   gatherer.digestrecord  11984      False             []      [2]   
500   gatherer.digestrecord  11996      False             []      [2]   
533   gatherer.digestrecord  12029      False             []      [2]   
...                     ...    ...        ...            ...      ...   
7018  gatherer.digestrecord  18514      False             []      [2]   
7040  gatherer.digestrecord  18536      False             []      [1]   
7469  gatherer.digestrecord  18965      False             []      [2]   
7472  gatherer.digestrecord  18968      False             []      [2]   
7597  gatherer.digestrecord  19093      False             []      [2]   

         state subcategory                                              title  \
477   FILTERED         NaN                       Cloud Native News - CNN21/27   
485    UNKNOWN         NaN       A Tutorial on Verifying LinkedList Using KeY   
488    UNKNOWN         NaN                   Expressive Animator v0.2.0 alpha   
500    UNKNOWN         NaN       NetBSD/Desktop: Scalable Workstation Systems   
533   FILTERED         NaN  Undocumented x86 instructions to control the C...   
...        ...         ...                                                ...   
7018  FILTERED         NaN                            Episode 387 - Azure Arc   
7040   IGNORED         NaN  Отечественная система видеосвязи TrueConf рабо...   
7469   UNKNOWN         NaN  Why brave browser sued newly braver browser? I...   
7472   UNKNOWN         NaN  Prebuilt Docker Images for Inference in Azure ...   
7597  FILTERED         NaN                IT Pros: Learn Azure Your Way Pt. 2   

                                                    url  
477         https://blog.nativecloud.dev/cnn-2021-26-2/  
485               https://ir.cwi.nl/pub/29986/29986.pdf  
488   https://medium.com/@expressivesuite/expressive...  
500   https://www.cs.stevens.edu/~jschauma/netbsd/ne...  
533   https://github.com/chip-red-pill/udbgInstr/raw...  
...                                                 ...  
7018  http://feedproxy.google.com/~r/theazurepodcast...

In [135]:
df.state.unique()

array(['FILTERED', 'IGNORED', 'IN_DIGEST', 'UNKNOWN', 'OUTDATED'],
      dtype=object)

In [144]:
df_pos = df.loc[(df.state == 'IN_DIGEST') | (df.state == 'OUTDATED')]

In [134]:
len(df.loc[(df.state == 'FILTERED') | (df.state == 'IGNORED')])

4874

In [136]:
len(df.loc[df.state == 'UNKNOWN'])

2462

In [100]:
len(df.loc[df.language == 'RUSSIAN'])

554

In [101]:
len(df.loc[df.download_status == 'success'])

7537